#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Sho Haneishi
# SPDX-License-Identifier: BSD-3-Clause

import sys

def check(s):
    try:
        return int(s)
    except:
        return float(s)

sig1 = 0
sig2 = 0
sig3 = 0

for line in sys.stdin:
    sig1 += check(line)
    sig2 += pow(check(line), 2)
    sig3 += pow(check(line), 3)

print("Σk =",sig1, "Σk^2 =",sig2, "Σk^3 =",sig3)


