#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Sho Haneishi
# SPDX-License-Identifier: BSD-3-Clause

import sys

def check(s):
    try:
        return int(s)
    except:
        return float(s)

sig1 = 0

for line in sys.stdin:
    sig1 += check(line)

print(sig1)


